### ISSUE TITLE
Is there a reason to prefer lockout not be fifo?

### ISSUE THREAD

**Issue by DiscordLiz** [mikeshardmind/async-utils#1]

**Comment by mikeshardmind** [comment]
Making it FIFO would increase the overhead of the underlying object.

This isn't intended as a primary synchronization method, but as a means of stopping the flow for an amount of time.

I may add other objects that are optimized to do both rather than require appropriate composition of them yourself in the future, but that can explode in number of objects, so I'm considering if it's worth it to make it easier for some people out of the box or not.

**Comment by mikeshardmind** [comment]
added a FIFO version in b162b652e257ccda3665c7a5a87df777e4d6937f feel free to compare, added due to non-trivial differences and not wanting to force users to wrap all uses of the other in a lock to retain fifo
